### ISSUE TITLE
How to programatically use this without logback.xml?

### ISSUE THREAD

**Issue by darrenhaken** [papertrail/logback-syslog4j#12]
I'm trying to integrate Papertrail with a Java framework called [Dropwizard](dropwizard.io) which uses YML for configuration rather than logback.xml.

I'm trying to programmatically configure papetrail/logback-syslog4j and pass in the config it needs. I've done this and yet Papertrail fails silently without any logs.

Here is a the method I've tried to use:

```Java
@Override
    public Appender<ILoggingEvent> build(LoggerContext context, String applicationName,
                                         LayoutFactory<ILoggingEvent> layoutFactory,
                                         LevelFilterFactory<ILoggingEvent> levelFilterFactory,
                                         AsyncAppenderFactory<ILoggingEvent> asyncAppenderFactory) {
        final Syslog4jAppender<ILoggingEvent> syslogAppender = new Syslog4jAppender<>();
        final TCPNetSyslogConfig syslogConfig = new TCPNetSyslogConfig();

        syslogConfig.setIdent(ident);
        syslogConfig.setHost(host);
        syslogConfig.setPort(port);
        syslogConfig.setFacility(facility.toLowerCase(Locale.ENGLISH));
        syslogConfig.setSendLocalName(sendLocalName);

        syslogAppender.setName("papertrail-syslog-tls");
        syslogAppender.setContext(context);

//        layoutFactory.build()

//        syslogAppender.setLayout(new ch.qos.logback.classic.PatternLayout());
        syslogAppender.setLayout(layoutFactory.build(context, TimeZone.getTimeZone("UTC")));
        syslogAppender.addFilter(levelFilterFactory.build(threshold));
        getFilterFactories().forEach(f -> syslogAppender.addFilter(f.build()));
        syslogAppender.setSyslogConfig(syslogConfig);

        syslogAppender.start();

        return wrapAsync(syslogAppender, asyncAppenderFactory);
    }
```

**Comment by troy** [comment]
@darrenhaken it looks like your issue was unintentionally empty. Could you edit it and add/re-add the more detailed explanation?

**Comment by darrenhaken** [comment]
@troy see the original post

**Comment by troy** [comment]
@darrenhaken: While Papertrail wrote and OSS'ed this in the interest of making an open standard (syslog) easier to adopt, it's not otherwise Papertrail-specific or Papertrail-related. We just try our best to be useful :) That said, @eric has the most experience with this, so if he knows the answer, he'll jump in.

**Comment by eric** [comment]
I haven't tried using this outside of with a `logback.xml`. The code looks reasonable, but I don't know a lot about the internals of logback.

**Comment by darrenhaken** [comment]
@troy and @eric thanks for chipping in, shame we can't resolve it

**Comment by troy** [comment]
@darrenhaken 2 ideas come to mind to troubleshoot this:

* try a different appender. Do you see any logs? If so, it's specific to this appender or to something it does (like SELinux blocking traffic from the JVM process)
* run strace against the JVM while generating a log message, and see where it leads :)
