### ISSUE TITLE
Error with TCP / TLS - maybe CA issue?

### ISSUE THREAD

**Issue by coopernurse** [papertrail/logback-syslog4j#5]
I just tried configuring this per the README (logback.xml is copy/paste from readme, substituting the host/port with my account settings).  A simple test results in:

```
SSLTCPNetSyslog: DOWN (org.productivity.java.syslog4j.SyslogRuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
```

UDP logging with this package (to same papertrailapp.com endpoint) works fine.

This is on Mac OS with JDK 1.8.0_25

If you can't easily repro this, I can post a full repro with logback.xml + Java code.  My understanding of the exception is that the JDK's built in cert chain can't validate your cert.

When I've configured papertrail with syslog forwarding I've had to install a .pem file - not sure if users of this package are expected to do something similar and register a separate keystore.

**Comment by troy** [comment]
@coopernurse I'm transitioning this into a Papertrail support request, since it's environment- and Papertrail-specific. Please expect another reply in your email inbox from `support@` later today or on Monday.
