### ISSUE TITLE
No route to host - IP address? Docker?

### ISSUE THREAD

**Issue by cap10morgan** [papertrail/logback-syslog4j#9]
I'm trying to use this in a Docker container, but I get `(SyslogWriter: TCPNetSyslog)  [org.productivity.java.syslog4j.SyslogRuntimeException: java.net.NoRouteToHostException: No route to host]` errors. However, from this very same container, `nmap -p 601 172.17.0.5` returns:

```
Nmap scan report for 172.17.0.5
Host is up (0.000085s latency).
PORT    STATE SERVICE
601/tcp open  syslog-conn
```

My logback.xml is:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
  <appender name="Syslog" class="com.papertrailapp.logback.Syslog4jAppender">
    <layout>
      <pattern>%-5level %logger{35}: %m%n%xEx</pattern>
    </layout>

    <syslogConfig class="org.productivity.java.syslog4j.impl.net.tcp.TCPNetSyslogConfig">
      <host>172.17.0.5</host>
      <port>601</port>
      <ident>election-notification-works</ident>
    </syslogConfig>
  </appender>

  <logger name="datomic" level="WARN"/>

  <logger name="election-notification-works" level="DEBUG"/>

  <root level="INFO">
    <appender-ref ref="Syslog"/>
  </root>
</configuration>
```

I'm running the app in question in WildFly 8.2.1.Final (also tried 9.0.2.Final to see if the latest release fixed anything, but it didn't seem to make a difference). I disabled WildFly's built-in logging and it does seem to be activating the logback configuration (as evidenced by the appearance of SyslogWriter in the error message).

Is this happening because I'm specifying an IP address instead of a hostname?

**Comment by troy** [comment]
Regarding your last question: probably :) The authors of this repo didn't write the `TCPNetSyslogConfig ` class, but from [this page](http://www.syslog4j.org/docs/javadoc/org/productivity/java/syslog4j/impl/net/AbstractNetSyslogConfig.html#host), I wouldn't be surprised if it required a hostname. Try it and see, even if it's just by defining one locally in `/etc/hosts`.

**Comment by cap10morgan** [comment]
Hostname makes no difference, I still get "No route to host."

**Comment by troy** [comment]
Hmm. I'm as stumped as you are. Thinking out loud, here's 3 things to try:

* tcpdump or another packet sniffer, and capturing/skimming all outbound and inbound traffic while a connection is trying to be established. You should see a connection attempt and an ICMP host unreachable response, and that'll show what it's trying to reach.
* strace ([example](http://help.papertrailapp.com/kb/configuration/troubleshooting-remote-syslog-reachability/#test-examine-logger-daemon-activity)) on the JVM while logging is occurring
* ensure SELinux and other unusual host-based protections aren't running. This seems unlikely in Docker, but it's always possible. Trying the same config on a standalone physical host built from a different distro might eliminate that whole part of the stack.
